services:

  redis:
    image: redis:7-alpine
    container_name: matstore_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: matstore_db
    environment:
      POSTGRES_DB: matstore
      POSTGRES_USER: matstore
      POSTGRES_PASSWORD: matstore123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    container_name: matstore_web
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --reload"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://matstore:matstore123@db:5432/matstore

  worker:
    build: .
    container_name: matstore_worker
    command: celery -A config worker --loglevel=info --concurrency=2 --without-heartbeat
    volumes:
      - .:/app
      - media_volume:/app/media
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://matstore:matstore123@db:5432/matstore
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
  static_volume:
  media_volume:
