[deploy]
# On enlève le migrate pour l'instant pour voir l'erreur Gunicorn
startCommand = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --log-level debug --access-logfile - --error-logfile -"
healthcheckPath = "/health/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"