# Generated by Django 6.0.2 on 2026-03-16 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('more_details', models.TextField(blank=True, max_length=500, null=True)),
                ('adress_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
