# Generated by Django 6.0.2 on 2026-03-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contactmessage_faq_alter_page_options_page_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='base_currency',
            field=models.CharField(choices=[('HTG', 'Gourde haïtienne (HTG)'), ('USD', 'Dollar américain (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'Livre sterling (GBP)'), ('CAD', 'Dollar canadien (CAD)'), ('CHF', 'Franc suisse (CHF)'), ('JPY', 'Yen japonais (JPY)'), ('MAD', 'Dirham marocain (MAD)'), ('XOF', 'Franc CFA (XOF)'), ('DZD', 'Dinar algérien (DZD)'), ('TND', 'Dinar tunisien (TND)'), ('BRL', 'Real brésilien (BRL)'), ('MXN', 'Peso mexicain (MXN)')], default='HTG', help_text='Devise dans laquelle les prix des produits sont saisis.', max_length=4),
        ),
        migrations.AlterField(
            model_name='setting',
            name='currency',
            field=models.CharField(choices=[('HTG', 'Gourde haïtienne (HTG)'), ('USD', 'Dollar américain (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'Livre sterling (GBP)'), ('CAD', 'Dollar canadien (CAD)'), ('CHF', 'Franc suisse (CHF)'), ('JPY', 'Yen japonais (JPY)'), ('MAD', 'Dirham marocain (MAD)'), ('XOF', 'Franc CFA (XOF)'), ('DZD', 'Dinar algérien (DZD)'), ('TND', 'Dinar tunisien (TND)'), ('BRL', 'Real brésilien (BRL)'), ('MXN', 'Peso mexicain (MXN)')], default='HTG', help_text="Devise d'affichage sur le site (conversion automatique).", max_length=4),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=4)),
                ('target_currency', models.CharField(max_length=4)),
                ('rate', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taux de change',
                'verbose_name_plural': 'Taux de change',
                'ordering': ['base_currency', 'target_currency'],
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
    ]
