# Generated by Django 6.0.2 on 2026-03-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='deliver_fee',
            field=models.FloatField(default='10'),
        ),
    ]
