# Generated by Django 6.0.2 on 2026-03-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_setting_deliver_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='deliver_fee',
        ),
    ]
