# Generated by Django 6.0.2 on 2026-03-17 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_revert_description_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('more_description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='payment_methodes/%Y/%m/%d/')),
                ('test_public_key', models.CharField(max_length=255)),
                ('test_private_key', models.CharField(max_length=255)),
                ('prod_public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('prod_private_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('billing_address', models.CharField(max_length=255)),
                ('shipping_address', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('taxe', models.FloatField()),
                ('order_cost', models.FloatField()),
                ('order_cost_ttc', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
                ('carrier_name', models.CharField(max_length=255)),
                ('carrier_price', models.FloatField()),
                ('payment_method', models.CharField(max_length=255)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('solde_price', models.FloatField()),
                ('regular_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('taxe', models.FloatField()),
                ('sub_total_ht', models.FloatField()),
                ('sub_total_ttc', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='shop.order')),
            ],
        ),
    ]
