# Generated by Django 6.0.2 on 2026-03-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_default_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non payé'), ('proof_submitted', 'Preuve envoyée'), ('verified', 'Vérifié'), ('paid', 'Payé')], default='unpaid', max_length=20, verbose_name='Statut paiement'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='apk_file',
            field=models.FileField(blank=True, help_text='Fichier APK Android (.apk). Laisser vide si non disponible.', null=True, upload_to='mobile/apk/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='apk_version',
            field=models.CharField(blank=True, help_text='Ex : 1.0.0 — affiché dans le bandeau.', max_length=20, null=True),
        ),
    ]
