# Generated by Django 6.0.2 on 2026-03-22 13:05

import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='apk_file',
            field=models.FileField(blank=True, help_text='Fichier APK Android (.apk uniquement). Laisser vide si non disponible.', null=True, upload_to='mobile/apk/', validators=[shop.validators.validate_apk_extension]),
        ),
        migrations.AlterField(
            model_name='setting',
            name='copyright',
            field=models.TextField(blank=True, default=''),
        ),
    ]
